In [12]:
import pandas as pd

In [13]:
url = 'https://raw.githubusercontent.com/KelvynAmaral/MLJourney/refs/heads/main/datasets/Tomato.csv'

In [34]:
df_excel = pd.read_excel("c:/Users/kelvyn.candido/Desktop/MLJourney/datasets/Chess.xlsx", sheet_name="Chess")

In [15]:
df_csv = pd.read_csv(url, sep=",")

In [16]:
df_csv.head()

Date Unit  Minimum  Maximum  Average  Market
0  2013-06-16   Kg       26       32     29.0  Tomato
1  2013-06-17   Kg       20       25     22.5  Tomato
2  2013-06-18   Kg       22       26     24.0  Tomato
3  2013-06-19   Kg       24       28     26.0  Tomato
4  2013-06-20   Kg       22       26     24.0  Tomato

In [17]:
df_excel.tail()

rated    created_at  last_move_at  turns victory_status winner  \
20053   True  1.499791e+12  1.499791e+12     24         resign  white   
20054   True  1.499698e+12  1.499699e+12     82           mate  black   
20055   True  1.499698e+12  1.499698e+12     35           mate  white   
20056   True  1.499696e+12  1.499697e+12    109         resign  white   
20057   True  1.499643e+12  1.499644e+12     78           mate  black   

      increment_code      white_id  white_rating            black_id  \
20053          10+10       belcolt          1691            jamboger   
20054           10+0      jamboger          1233  farrukhasomiddinov   
20055           10+0      jamboger          1219        schaaksmurf3   
20056           10+0  marcodisogno          1360            jamboger   
20057           10+0      jamboger          1235               ffbob   

       black_rating opening_eco                     opening_name  opening_ply  
20053          1220         A80                    Dutch Defense            2  
20054          1196         A41                     Queen's Pawn            2  
20055          1286         D00  Queen's Pawn Game: Mason Attack            3  
20056          1227         B07                     Pirc Defense            4  
20057          1339         D00  Queen's Pawn Game: Mason Attack            3

In [18]:
df_csv.shape

(2741, 6)

In [19]:
df_excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20058 entries, 0 to 20057
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   rated           20058 non-null  bool   
 1   created_at      20058 non-null  float64
 2   last_move_at    20058 non-null  float64
 3   turns           20058 non-null  int64  
 4   victory_status  20058 non-null  object 
 5   winner          20058 non-null  object 
 6   increment_code  20058 non-null  object 
 7   white_id        20058 non-null  object 
 8   white_rating    20058 non-null  int64  
 9   black_id        20058 non-null  object 
 10  black_rating    20058 non-null  int64  
 11  opening_eco     20058 non-null  object 
 12  opening_name    20058 non-null  object 
 13  opening_ply     20058 non-null  int64  
dtypes: bool(1), float64(2), int64(4), object(7)
memory usage: 2.0+ MB


In [20]:
df_excel.describe()

created_at  last_move_at         turns  white_rating  black_rating  \
count  2.005800e+04  2.005800e+04  20058.000000  20058.000000  20058.000000   
mean   6.321335e+16  6.313080e+16     60.465999   1596.631868   1588.831987   
std    7.292307e+16  7.290633e+16     33.570585    291.253376    291.036126   
min    1.376772e+12  1.376772e+12      1.000000    784.000000    789.000000   
25%    1.498313e+12  1.498315e+12     37.000000   1398.000000   1391.000000   
50%    1.504366e+12  1.504367e+12     55.000000   1567.000000   1562.000000   
75%    1.486680e+17  1.486680e+17     79.000000   1793.000000   1784.000000   
max    1.504470e+17  1.504470e+17    349.000000   2700.000000   2723.000000   

        opening_ply  
count  20058.000000  
mean       4.816981  
std        2.797152  
min        1.000000  
25%        3.000000  
50%        4.000000  
75%        6.000000  
max       28.000000

In [21]:
df_excel.describe().T

count          mean           std           min           25%  \
created_at    20058.0  6.321335e+16  7.292307e+16  1.376772e+12  1.498313e+12   
last_move_at  20058.0  6.313080e+16  7.290633e+16  1.376772e+12  1.498315e+12   
turns         20058.0  6.046600e+01  3.357058e+01  1.000000e+00  3.700000e+01   
white_rating  20058.0  1.596632e+03  2.912534e+02  7.840000e+02  1.398000e+03   
black_rating  20058.0  1.588832e+03  2.910361e+02  7.890000e+02  1.391000e+03   
opening_ply   20058.0  4.816981e+00  2.797152e+00  1.000000e+00  3.000000e+00   

                       50%           75%           max  
created_at    1.504366e+12  1.486680e+17  1.504470e+17  
last_move_at  1.504367e+12  1.486680e+17  1.504470e+17  
turns         5.500000e+01  7.900000e+01  3.490000e+02  
white_rating  1.567000e+03  1.793000e+03  2.700000e+03  
black_rating  1.562000e+03  1.784000e+03  2.723000e+03  
opening_ply   4.000000e+00  6.000000e+00  2.800000e+01

In [22]:
set(df_excel['victory_status']) #Analisando coluna especifica.

{'draw', 'mate', 'outoftime', 'resign'}

In [23]:
df_csv.head()

Date Unit  Minimum  Maximum  Average  Market
0  2013-06-16   Kg       26       32     29.0  Tomato
1  2013-06-17   Kg       20       25     22.5  Tomato
2  2013-06-18   Kg       22       26     24.0  Tomato
3  2013-06-19   Kg       24       28     26.0  Tomato
4  2013-06-20   Kg       22       26     24.0  Tomato

In [24]:
def media_tomate(media):
  if media >= 40 and media <= 70:
    return "Tomatão"
  elif media >= 20 and media <= 40:
    return "Tomate medio"
  else:
    return "Tomatinho"


In [25]:
df_csv["Categoria_Tomate"] = df_csv["Average"].apply(media_tomate)

In [26]:
df_csv.tail()

Date Unit  Minimum  Maximum  Average  Market Categoria_Tomate
2736  2021-05-09   Kg       10       15     12.5  Tomato        Tomatinho
2737  2021-05-10   Kg       10       15     12.5  Tomato        Tomatinho
2738  2021-05-11   Kg       10       15     12.5  Tomato        Tomatinho
2739  2021-05-12   Kg       30       35     32.5  Tomato     Tomate medio
2740  2021-05-13   Kg       35       40     37.5  Tomato     Tomate medio

In [27]:
df_csv.groupby("Categoria_Tomate").describe()

Minimum                                                       \
                   count       mean        std   min   25%   50%   75%    max   
Categoria_Tomate                                                                
Tomate medio      1296.0  26.611111   5.537098  15.0  20.0  25.0  30.0   38.0   
Tomatinho          491.0  32.737271  28.755092   8.0  15.0  15.0  70.0  115.0   
Tomatão            954.0  47.818658   8.203065  30.0  40.0  45.0  55.0   65.0   

                 Maximum             ...              Average             \
                   count       mean  ...   75%    max   count       mean   
Categoria_Tomate                     ...                                   
Tomate medio      1296.0  32.310957  ...  35.0   44.0  1296.0  29.461034   
Tomatinho          491.0  38.285132  ...  75.0  120.0   491.0  35.511202   
Tomatão            954.0  55.009434  ...  60.0   75.0   954.0  51.414046   

                                                            
                        std   min   25%   50%   75%    max  
Categoria_Tomate                                            
Tomate medio       5.408186  20.0  25.0  29.5  32.5   39.5  
Tomatinho         29.170634  10.0  17.5  17.5  72.5  117.5  
Tomatão            8.272792  40.0  45.0  50.0  57.5   70.0  

[3 rows x 24 columns]

# Numpy


In [28]:
import numpy as np

In [29]:
set(df_csv['Categoria_Tomate'])

{'Tomate medio', 'Tomatinho', 'Tomatão'}

In [30]:
arr_list = np.array([1, 2, 3, 4, 5, 5, 7, 8])

In [31]:
print(arr_list)

[1 2 3 4 5 5 7 8]


In [32]:
arr_zeros  = np.zeros((4 , 6)) #Criando um array de zeros com 4 linhas e 6 colunas.
print(arr_zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
